### ISSUE TITLE
--include-only doesn't work

### ISSUE THREAD

**Issue by fetis** [mateodelnorte/loop#30]
## 🐛 Bug Report

I'm trying to run this on Windows

## To Reproduce

`loop --include-only services "echo 1"`

Output
```
servicesecho 1:
servicesecho 1: command '--include-only' exited with error: Error: spawnSync C:\Windows\system32\cmd.exe ENOENT
```

## Expected behavior

iterate `services` directory

**Comment by mateodelnorte** [comment]
Can you provide the actual command you're running?

**Comment by fetis** [comment]
> Can you provide the actual command you're running?
the command is in the bug description. I tried it from command prompt and from `scripts` section of package.json

**Comment by mateodelnorte** [comment]
Woops. Didn't see it while viewing on phone. Does `loop "echo 1" --include-only services` work? Ordering matters. The command needs to be first. I'd be pretty surprised if this stopped working.

**Comment by patrickleet** [comment]
could you paste your .meta file as well?

**Comment by patrickleet** [comment]
if you have multiple dirs in `services` you could run `loop` from that directory instead of the one above it

**Comment by fetis** [comment]
> Woops. Didn't see it while viewing on phone. Does loop "echo 1" --include-only services work? Ordering matters. The command needs to be first. I'd be pretty surprised if this stopped working.

this works! doc wasn't clear about it, so I assumed standard convention like params first, command last

**Comment by mateodelnorte** [comment]
Woot woot! Happy to take an update PR to the docs if you think that'd be helpful. Cheers.

**Comment by devpascoe** [comment]
> if you have multiple dirs in `services` you could run `loop` from that directory instead of the one above it

I found this to work @patrickleet 
loop "echo 1" --cwd services
