### ISSUE TITLE
--quiet for reduced output

### ISSUE THREAD

**Issue by skeggse** [mateodelnorte/loop#39]
## 🚀 Feature Proposal

Implement the flag `--quiet` (alias `-q`, perhaps). This would omit the printing of the normal directory information.

## Motivation

If I run `loop 'git status -s'`, I get hundreds of extra lines that don't help me figure out which repos have uncommitted changes. I'd like to get a list of only those repos that do - and `--quiet` would eliminate the extra content.

## Example

```sh
$ loop 'status="$(git status -s)" && if [ "$status" != "" ]; then pwd && echo "$status"; fi'
/home/.../src/app:
/home/.../src/app ✓

/home/.../src/dep:
/home/.../src/dep ✓

/home/.../src/other:
/home/.../src/other
 M README.md
/home/.../src/other ✓
```

Becomes

```sh
$ loop -q 'status="$(git status -s)" && if [ "$status" != "" ]; then pwd && echo "$status"; fi'
/home/.../src/other
 M README.md
```

**Comment by skeggse** [comment]
:(

**Comment by mateodelnorte** [comment]
Hey @skeggse. Interested in making a PR for this?

**Comment by skeggse** [comment]
Quite possibly - I'll see if I can take a look later this week.
